<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite parallel="tests" name="Failed suite [Suite]" guice-stage="DEVELOPMENT" verbose="0">
  <listeners>
    <listener class-name="akhiraacademy.TestComponents.Listeners"/>
  </listeners>
  <test thread-count="5" parallel="tests" name="ErrorTest(failed)" verbose="0">
    <classes>
      <class name="akhiraacademy.Tests.ErrorValidations">
        <methods>
          <include name="LoginErrorValidation"/>
        </methods>
      </class> <!-- akhiraacademy.Tests.ErrorValidations -->
    </classes>
  </test> <!-- ErrorTest(failed) -->
  <test thread-count="5" parallel="tests" name="SubmitTest(failed)" verbose="0">
    <classes>
      <class name="akhiraacademy.Tests.FinalSolution">
        <methods>
          <include name="LogoutApplication"/>
          <include name="submitOrder" invocation-numbers="1"/>
        </methods>
      </class> <!-- akhiraacademy.Tests.FinalSolution -->
    </classes>
  </test> <!-- SubmitTest(failed) -->
</suite> <!-- Failed suite [Suite] -->
